---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2018-08-14-00:07:19
---

RoleAction = {}

RoleAction.RoleInfo = "push@role_info"
---@class Modules.Role.Service.RoleService : Core.Ioc.BaseService
local BaseService = require("Core.Ioc.BaseService")
local RoleService = class("RoleService",BaseService)
local RoleVo = require("Modules.Role.Vo.RoleVo")

function RoleService:Ctor()
    nmgr:AddPush(RoleAction.RoleInfo, handler(self,self.OnRoleInfo))
end

---push
function RoleService:OnRoleInfo(response)
    log("角色进入游戏:"..response.roleInfo.roleName)
    self.roleModel.mainRoleInfo = RoleVo.New(response.roleInfo)
end

return RoleService
