---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/6/30 0:02
--- 场景的基类
---

---@class Modules.World.Scenes.BaseScene : Core.LuaMonoBehaviour
local LuaMonoBehaviour = require('Core.LuaMonoBehaviour')
local BaseScene = class("BaseScene",LuaMonoBehaviour)

function BaseScene:Ctor()
    LuaMonoBehaviour.Ctor(self)
    self:Init()
end

function LoginScene:Init()
    self.uiCanvas = GameObject.Instantiate(assetsMgr:LoadPrefab("Prefabs/UI/Common"))
    vmgr:SetScene(self)
end

return BaseScene