---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/8/14 22:07
---

---@class Modules.World.Scenes.LoadingScene : Modules.World.Scenes.BaseScene
local BaseScene = require('Modules.World.Scenes.BaseScene')
local LoadingScene = class("LoadingScene",BaseScene)

function LoadingScene:Ctor()
    BaseScene.Ctor(self)
end

function LoadingScene:OnEnterScene()
    vmgr:LoadView(ViewConfig.Loading)
    --vmgr:LoadView(ViewConfig.NewbieWelcome)
end

return LoadingScene