---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/8/14 1:01
---

---@class Modules.World.Scenes.LobbyScene : Modules.World.Scenes.BaseScene
local BaseScene = require('Modules.World.Scenes.BaseScene')
local LobbyScene = class("LobbyScene",BaseScene)

function LobbyScene:Ctor()
    BaseScene.Ctor(self)
end

function LobbyScene:OnEnterScene()
    --vmgr:LoadView(ViewConfig.RoleInfo)
    --vmgr:LoadView(ViewConfig.NewbieWelcome)
end

return LobbyScene