---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/6/29 23:35
---

require "Config.ViewConfig"
require "Config.WorldConfig"

log("Global config has all require")