ViewConfig={}
ViewConfig.Login={name="Login",prefab="Prefabs/UI/Login/LoginWnd.prefab",}
ViewConfig.Notice={name="Notice",prefab="Prefabs/UI/Login/NoticeWnd.prefab",}
ViewConfig.World={name="World",prefab="Prefabs/UI/Common/World.prefab",}
ViewConfig.ServerList={name="ServerList",prefab="Prefabs/UI/Login/ServerListWnd.prefab",}
ViewConfig.LoginScene={name="LoginScene",prefab="Prefabs/UI/Login/LoginScene.prefab",}
ViewConfig.RoleCreate={name="RoleCreate",prefab="Prefabs/UI/Login/RoleCreate.prefab",}
ViewConfig.RoleSelect={name="RoleSelect",prefab="Prefabs/UI/Login/RoleSelectWnd.prefab",}
ViewConfig.NewbieWelcome={name="NewbieWelcome",prefab="Prefabs/UI/Newbie/NewbieWelcome.prefab",}
ViewConfig.RoleInfo={name="RoleInfo",prefab="Prefabs/UI/Role/RoleInfo.prefab",}
