---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/6/29 23:58
---

---@class Modules.Notice.View.WorldMdr : Core.Ioc.BaseMediator
local BaseMediator = require("Core.Ioc.BaseMediator")
local WorldMdr = class("WorldMdr",BaseMediator)

function WorldMdr:OnInit()
    vmgr:LoadView(ViewConfig.Login)
end

return WorldMdr