---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/6/14 0:16
---

---@class Core.Ioc.BaseMediator : Core.LuaMonoBehaviour
local LuaMonoBehaviour = require('Core.LuaMonoBehaviour')
local BaseMediator = class("BaseMediator",LuaMonoBehaviour)

function BaseMediator:Ctor()

end

return BaseMediator