---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/6/14 0:16
---

---@class Core.Ioc.BaseMediator : Core.LuaMonoBehaviour
local LuaMonoBehaviour = require('Core.LuaMonoBehaviour')
local BaseMediator = class("BaseMediator",LuaMonoBehaviour)
local NetworkListener = require("Manager.NetworkListener")

function BaseMediator:Ctor()
    LuaMonoBehaviour.Ctor(self)

    self.listener = NetworkListener.New()
    self.removeCallback = nil
end

function BaseMediator:Start()
    self:OnInit()
    self:OnAutoRegisterEvent()
    self:RegisterListeners()

    nmgr:AddListener(self.listener)
end

function BaseMediator:OnInit()

end

function BaseMediator:RegisterListeners()

end

function BaseMediator:AddPush(action, callback)
    if callback ~= nil then
        self.listener:addPushCallback(action, callback)
    end
end

--自动注册事件
function BaseMediator:OnAutoRegisterEvent()
    local buttons = LuaHelper.GetChildrenButtons(self.gameObject)
    for i = 0,buttons.Length - 1 do
        local funName = "On_Click_"..buttons[i].gameObject.name
        if self[funName] then
            print(funName)
            LuaHelper.AddButtonClick(buttons[i].gameObject,handler(self,self[funName]))
        end
    end
end

function BaseMediator:RegisterClick(go, clickFun)
    LuaHelper.AddButtonClick(go,handler(self,clickFun))
end

function BaseMediator:DoRemove(callback)
    self.removeCallback = callback
end

function BaseMediator:OnDestroy()
    print("OnDestroy view: "..self.viewInfo.name)
    self:Dispose()
    nmgr:RemoveListener(self.listener)
    self:OnRemove()
    if self.removeCallback ~= nil then
        self.removeCallback(self)
    end
    self.viewInfo.status = ViewStatus.Unloaded
end

function BaseMediator:OnRemove()

end

return BaseMediator