---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhengnan.
--- DateTime: 2018/6/19 18:18
---

---@class Core.Ioc.BaseVo : Core.LuaObject
local LuaObject = require('Core.LuaObject')
local BaseVo = class("BaseVo",LuaObject)

function BaseVo:Ctor()

end

return BaseVo