---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhengnan.
--- DateTime: 2018/6/19 18:18
---

---@class Core.Ioc.BaseService : Core.LuaObject
local LuaObject = require('Core.LuaObject')
local BaseService = class("BaseService",LuaObject)

function BaseService:Ctor()

end

return BaseService