---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhengnan.
--- DateTime: 2018/6/12 10:37
---

local IocContext = require("Core.Ioc.IocContext")
local ModelContext = class("ModelContext",IocContext)

function ModelContext:Ctor(binder)
    self.binder = binder
end

function ModelContext:Launch()
    --TODO
	self.binder:Bind(require("Modules.Login.Model.LoginModel")):ToSingleton()
	self.binder:Bind(require("Modules.Newbie.Model.NewbieModel")):ToSingleton()
	self.binder:Bind(require("Modules.Role.Model.RoleModel")):ToSingleton()
    --TODO
end

return ModelContext
