---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/1/18 23:21
---

local LuaMonoBehaviour = require("Betel.LuaMonoBehaviour")
---@class Betel.UI.BaseList : Betel.LuaMonoBehaviour
---@field listView ListView
---@field adapter LuaListViewAdapter
---@field cell LuaListViewCell
---@field dataList Betel.List
local BaseList = class("Betel.UI.BaseList",LuaMonoBehaviour)

---@param gameObject UnityEngine.GameObject
---@param itemRendererClass table
function BaseList:Ctor(gameObject, itemRendererClass)
    BaseList.super.Ctor(self,gameObject)
    self.itemRendererClass = itemRendererClass
    self.listView = gameObject:FindChild("Content"):GetCom("ListView")
    self.adapter = self.listView.Adapter
    --self.cell = self.adapter.gameObject:GetCom("LuaListViewCell")
end

---@param dataList Betel.List
function BaseList:SetData(dataList)
    self.dataList = dataList
    self.adapter:Init(self.dataList:Size(),handler(self,self.OnItemCreate))
    self.listView:RefreshData()
end

---@param cell LuaListViewCell
---@param index number
function BaseList:OnItemCreate(cell, index)
    local item = self.itemRendererClass.New(cell.gameObject)
    item:Update(self.dataList[index + 1],index + 1)
end

return BaseList