---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/1/20 1:22
---

local Event = require("Betel.Events.Event")
---@class Betel.UI.ListViewEvent : Betel.Events.Event
local ListViewEvent = class("Game.UI.ListViewEvent", Event)

ListViewEvent.ItemClick = "ItemClick"

function ListViewEvent:Ctor(type)
    ListViewEvent.super.Ctor(self, type)
end

return ListViewEvent