---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/1/20 1:22
---

---@class Betel.UI.ListViewEvent
local ListViewEvent = class("Betel.UI.ListViewEvent")

ListViewEvent.ItemClick = "ItemClick"

function ListViewEvent:Ctor()

end

return ListViewEvent