---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2020/6/19 23:00
---

local BaseList = require("Betel.UI.BaseList")
---@class Betel.UI.PositionList : Betel.UI.BaseList
---@field New fun(gameObject:UnityEngine.GameObject, itemRendererClass:table, noPassEvent:boolean):Betel.UI.PositionList
---@field posList table<number, UnityEngine.RectTransform>
local PositionList = class("Betel.UI.PositionList",BaseList)

---@param gameObject UnityEngine.GameObject
---@param itemRendererClass table
function PositionList:Ctor(gameObject, itemRendererClass, noPassEvent)
    PositionList.super.Ctor(self,gameObject, itemRendererClass, noPassEvent)
end

---@param posList table<number, UnityEngine.RectTransform>
function PositionList:SetPosList(posList)
    self.posList = posList
end

---@param cell EasyList.LuaListViewCell
---@param index number
---@return Betel.UI.ListItemRenderer
function PositionList:OnItemCreate(cell, index)
    local item = PositionList.super.OnItemCreate(self,cell, index)---@type Betel.UI.ListItemRenderer
    item.transform.localPosition = self.posList[index].localPosition
    return item
end

return PositionList