---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2020/6/19 23:00
---


local BaseList = require("Betel.UI.BaseList")
---@class Betel.UI.TableList : Betel.UI.BaseList
---@field New fun(gameObject:UnityEngine.GameObject, itemRendererClass:table, noPassEvent:boolean):Betel.UI.TableList
local TableList = class("Betel.UI.TableList",BaseList)

---@param gameObject UnityEngine.GameObject
---@param itemRendererClass table
function TableList:Ctor(gameObject, itemRendererClass, noPassEvent)
    TableList.super.Ctor(self,gameObject, itemRendererClass, noPassEvent)
    self.listView = GetListView(gameObject:FindChild("Content"))
    self.adapter = self.listView.Adapter
end

---@param cell EasyList.LuaListViewCell
---@param index number
function TableList:OnItemCreate(cell, index)
    return TableList.super.OnItemCreate(self, cell, index)
end

return TableList