---
--- Generated by Tools
--- Created by zhengnan.
--- DateTime: 2018-06-19-16:04:47
---

---@class Modules.Notice.Model.NoticeModel : Core.Ioc.BaseModel
local BaseModel = require("Core.Ioc.BaseModel")
local NoticeModel = class("NoticeModel",BaseModel)

function NoticeModel:Ctor()
    
end

return NoticeModel
