---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhengnan.
--- DateTime: 2019/5/20 18:34
---

local Math3D = {}

--获取一个随机数数组
---@param src UnityEngine.Transform
---@param dst UnityEngine.Transform
function Math3D.LookAt_XZ(src, dst)
    local dst = Vector3.New(dst.position.x, src.position.y, dst.position.z)
    src:LookAt(dst)
end

return Math3D