---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhengnan.
--- DateTime: 2019/5/20 18:34
---

local Math3D = {}

--获取一个随机数数组
function Math3D.GetRandomArray(n)
    local map = {}
    local list = {}
    for i = 1, n do
        local r = math.random(i, n)
        local a = r
        if map[r] then
            a = map[r]
        end
        table.insert(list, a)
        map[r] = map[i] or i
    end
    return list
end

return Math3D