---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhengnan.
--- DateTime: 2018/6/20 16:21
--- 视图管理d
---

---@class Manager.ViewManager : Core.LuaMonoBehaviour
local LuaMonoBehaviour = require('Core.LuaMonoBehaviour')
local ViewManager = class("ViewManager",LuaMonoBehaviour)

function ViewManager:Ctor()

end

return ViewManager