---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhengnan.
--- DateTime: 2018/6/20 16:21
--- 视图管理d
---

---@class Manager.ViewManager : Core.LuaMonoBehaviour
---@field public scene Modules.World.Scenes.BaseScene
local LuaMonoBehaviour = require('Core.LuaMonoBehaviour')
local ViewManager = class("ViewManager",LuaMonoBehaviour)

require("Config.ViewConfig")
local IocBootstrap = require("Core.Ioc.IocBootstrap").New()
local ViewStatus = {}
ViewStatus.Loading = "Loading"
ViewStatus.Loaded = "Loaded"
ViewStatus.Unloading = "Unloading"
ViewStatus.Unloaded = "Unloaded"

function ViewManager:Ctor()
    IocBootstrap:Launch()
    --self.viewCache = {}
    --self.viewList = List.New()
end

---@param scene Modules.World.Scenes.BaseScene
function ViewManager:SetScene(scene)
    self.scene = scene
end

---@param viewInfo Core.ViewInfo
function ViewManager:LoadView(viewInfo)
    self:DoLoadViewCo(viewInfo)
end

---@param viewInfo Core.ViewInfo
function ViewManager:DoLoadViewCo(viewInfo)
    if viewInfo == nil then
        logError("'viewInfo' param is nil")
        return
    end

    if viewInfo.status == nil or viewInfo.status == ViewStatus.Unloaded then
        viewInfo.status = ViewStatus.Loading
        self:LoadViewPrefab(viewInfo,function (go)
            self:CreateView(viewInfo,go)
            viewInfo.status = ViewStatus.Loaded
        end)
    else
        if viewInfo.status == ViewStatus.Loading or
            viewInfo.status == ViewStatus.Unloading or
            viewInfo.status == ViewStatus.Loaded then
            logError("View {0} status is {1} ,you can't load this view",viewInfo.name, viewInfo.status)
        end
    end
end

---@param viewInfo Core.ViewInfo
---@param callback function
function ViewManager:LoadViewPrefab(viewInfo,callback)
    local prefab = self:LoadAsset(viewInfo.prefab)
    if prefab then
        local go = GameObject.Instantiate(prefab)
        callback(go)
    end
end

---@param viewInfo Core.ViewInfo
---@param go UnityEngine.GameObject
function ViewManager:CreateView(viewInfo,go)
    local mdrType = IocBootstrap.mediatorContext:GetMediator(viewInfo.name)
    if mdrType == nil then
        logError("view:'{0}' has not register", viewInfo.name)
        return
    end
    local mdr = mdrType.New()
    if viewInfo ~= ViewConfig.World then
        mdr.scene = self.scene
        mdr.uiCanvas = self.scene.uiCanvas
        go.transform:SetParent(self.scene.uiCanvas.transform)
    end
    mdr.gameObject = go
    go.name = viewInfo.name .. " - " ..go.name
    go.transform.transform.localPosition = Vector3.zero
    go.transform.transform.localEulerAngles = Vector3.zero
    go.transform.transform.localScale = Vector3.one

    mdr:AddLuaMonoBehaviour(go,"Mediator")
end

return ViewManager