---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/1/20 1:17
---

---@class Betel.Events.Event
local Event = class("Betel.Events.Event")

Event.Update = "Update"
Event.LateUpdate = "LateUpdate"
Event.FixedUpdate = "FixedUpdate"

function Event:Ctor()

end

return Event