---
--- Generated by Tools
--- Created by zhengnan.
--- DateTime: 2018-06-19-16:04:56
---

---@class Modules.Login.Service.LoginService : Core.Ioc.BaseService
local BaseService = require("Core.Ioc.BaseService")
local LoginService = class("LoginService",BaseService)

function LoginService:Ctor()
    
end

return LoginService
