---
--- Generated by Tools
--- Created by zhengnan.
--- DateTime: 2018-06-19-18:06:57
---

---@class Modules.Notice.View.NoticeMdr : Core.Ioc.BaseMediator
local BaseMediator = require("Core.Ioc.BaseMediator")
local NoticeMdr = class("NoticeMdr",BaseMediator)

function NoticeMdr:OnInit()
    
end

return NoticeMdr
