---
--- Generated by Tools
--- Created by zhengnan.
--- DateTime: 2018-06-19-16:04:49
---

---@class Modules.Notice.Service.NoticeService : Core.Ioc.BaseService
local BaseService = require("Core.Ioc.BaseService")
local NoticeService = class("NoticeService",BaseService)

function NoticeService:Ctor()
    
end

return NoticeService
