---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/6/10 20:56
---

---UnityEngine
GameObject = UnityEngine.GameObject;
Application = UnityEngine.Application;
PlayerPrefs = UnityEngine.PlayerPrefs;

---Framework
logger = Logger