---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/6/11 0:23
---

require "Core.String"
require "Core.Function"
require "Core.Define"
require "Core.Log"
require "Core.Res"

log("Global define has all require")