---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/6/11 0:23
---

require "Betel.string"
require "Betel.Function"
require "Betel.Define"
require "Betel.Tools"
require "Betel.Log"
require "Betel.Res"

log("Global define has all require")