---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/6/12 0:43
---

--- 是否将日志输出到控制台
logger.GetInstance().LogInfoToConsole = true;
--- 是否输出一般日志的堆栈
logger.GetInstance().LogInfoTraceStack = false;
--- 是否输出到文本文件
logger.GetInstance().WriteToFile = true;

function log(msg,...)
    local args = Tools.GetArgs(...)
    local argNum = #args
    if argNum == 1 then
        logger.Info(msg,args[1])
    elseif argNum == 2 then
        logger.Info(msg,args[1],args[2])
    elseif argNum == 3 then
        logger.Info(msg,args[1],args[2],args[3])
    elseif argNum == 4 then
        logger.Info(msg,args[1],args[2],args[3],args[4])
    elseif argNum == 5 then
        logger.Info(msg,args[1],args[2],args[3],args[4],args[5])
    elseif argNum == 6 then
        logger.Info(msg,args[1],args[2],args[3],args[4],args[5],args[6])
    elseif argNum == 7 then
        logger.Info(msg,args[1],args[2],args[3],args[4],args[5],args[6],args[7])
    elseif argNum == 8 then
        logger.Info(msg,args[1],args[2],args[3],args[4],args[5],args[6],args[7],args[8])
    elseif argNum == 9 then
        logger.Info(msg,args[1],args[2],args[3],args[4],args[5],args[6],args[7],args[8],args[9])
    elseif argNum == 10 then
        logger.Info(msg,args[1],args[2],args[3],args[4],args[5],args[6],args[7],args[8],args[9],args[10])
    else
        logger.Info(msg,args)
    end
end

function logError(msg,...)
    local args = Tools.GetArgs(...)
    local argNum = #args
    if argNum == 1 then
        logger.Error(msg,args[1])
    elseif argNum == 2 then
        logger.Error(msg,args[1],args[2])
    elseif argNum == 3 then
        logger.Error(msg,args[1],args[2],args[3])
    elseif argNum == 4 then
        logger.Error(msg,args[1],args[2],args[3],args[4])
    elseif argNum == 5 then
        logger.Error(msg,args[1],args[2],args[3],args[4],args[5])
    elseif argNum == 6 then
        logger.Error(msg,args[1],args[2],args[3],args[4],args[5],args[6])
    elseif argNum == 7 then
        logger.Error(msg,args[1],args[2],args[3],args[4],args[5],args[6],args[7])
    elseif argNum == 8 then
        logger.Error(msg,args[1],args[2],args[3],args[4],args[5],args[6],args[7],args[8])
    elseif argNum == 9 then
        logger.Error(msg,args[1],args[2],args[3],args[4],args[5],args[6],args[7],args[8],args[9])
    elseif argNum == 10 then
        logger.Error(msg,args[1],args[2],args[3],args[4],args[5],args[6],args[7],args[8],args[9],args[10])
    else
        logger.Error(msg)
    end
end

function logWarn(msg,...)
    local arg = ...
    logger.Warning(msg,arg)
end

function logStack()
    logger.Error(debug.traceback("",2))
end
