---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/1/9 1:33
---

Res = {}

assetsMgr = Framework.GameManager.GetAssetsManager()

function Res.LoadPrefab(url)
    return assetsMgr:LoadPrefab(url);
end