---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2019/1/9 1:33
---

Res = {}

assetsMgr = Framework.GameManager.GetAssetsManager()


---@param path string
---@return string
function Res.LoadText(path)
    return assetsMgr:LoadText(path);
end

---@param path string
---@return UnityEngine.GameObject
function Res.LoadPrefab(path)
    return assetsMgr:LoadPrefab(path);
end

---@param path string
---@return UnityEngine.Sprite
function Res.LoadSprite(path)
    return assetsMgr:LoadSprite(path);
end
