---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2018-06-19-00:17:42
---

---@class Modules.Login.View.LoginMdr : Core.Ioc.BaseMediator
local BaseMediator = require("Core.Ioc.BaseMediator")
local LoginMdr = class("LoginMdr",BaseMediator)

function LoginMdr:OnInit()
    print("MVC 测试")
end

return LoginMdr
