---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2018-07-13-00:00:21
---

---@class Modules.Login.View.ServerListMdr : Core.Ioc.BaseMediator
local BaseMediator = require("Core.Ioc.BaseMediator")
local ServerListMdr = class("ServerListMdr",BaseMediator)

function ServerListMdr:OnInit()
    self.srvList = self.gameObject:FindChild("ScrollList"):GetCom("ScrollList")
    self.SrvItem = self.gameObject:FindChild("SrvItem")
    self.SrvItem:SetActive(false)
    self:InitSrvList()
end

function ServerListMdr:InitSrvList()
    LuaHelper.AddScrollListOnItemRender(self.srvList,function(index, item)
        local server = self.loginModel.serverList[(index + 1) % 2 + 1]
        local itemObj = item.gameObject
        itemObj:SetText("Text", server.name)
        itemObj:SetText("Toggle/Label", server.host)
        itemObj:SetActive(true)
    end)
    self.srvList.ChildCount = 10 * #self.loginModel.serverList
    self.srvList:SetItem(self.SrvItem)
end

return ServerListMdr
