using UnityEngine;
using UnityEngine.Serialization;

namespace ToLuaSupport
{
    public class ToLuaSetting : ScriptableObject
    {
        public string ViewConfigPath = "Assets/Lua/Game/Config/ViewConfig.lua";
        public string ModulesDir = "Lua/Game/Modules/";
        public string PrefabsRootDir = "Res/Prefabs/UI/";
        public string MediatorContextPath = "Assets/Lua/Game/Core/Ioc/MediatorContext.lua";
        public string ModelContextPath = "Assets/Lua/Game/Core/Ioc/ModelContext.lua";
        public string ServiceContextPath = "Assets/Lua/Game/Core/Ioc/ServiceContext.lua";
        public string PackageRoot = "Game.Modules";
        
        public string MODULE_NAME = "$MODULE_NAME$";

        public string Module_name = "$Module_name$";

        public string CLASS_NAME = "$CLASS_NAME$";

        public string INSTANCE_NAME = "$INSTANCE_NAME$";

        public string MODULE_PACKER = "$MODULE_PACKER$";

        public string CLASS_PACKER = "$CLASS_PACKER$";

        public string SUPER_CLASS_NAME = "$SUPER_CLASS_NAME$";

        public string SUPER_CLASS_PACKER = "$SUPER_CLASS_PACKER$";

        //一般的类文件
        public string LuaClassFile =
            @"---
--- Generated by Tools
--- Created by {0}.
--- DateTime: {1}
---

---@class $CLASS_PACKER$.$CLASS_NAME$ : Core.LuaObject
local LuaObject = require('Betel.LuaObject')
local $CLASS_NAME$ = class('$CLASS_PACKER$.$CLASS_NAME$',LuaObject)

function $CLASS_NAME$:Ctor()
    
end

return $CLASS_NAME$
";

        //有继承的类文件
        public string LuaSuperClassFile =
            @"---
--- Generated by Tools
--- Created by {0}.
--- DateTime: {1}
---

local $SUPER_CLASS_NAME$ = require('$SUPER_CLASS_PACKER$')
local $CLASS_NAME$ = class('$CLASS_PACKER$.$CLASS_NAME$',$SUPER_CLASS_NAME$)

function $CLASS_NAME$:Ctor()
    
end

return $CLASS_NAME$
";

        //Mediator类文件
        public string LuaMdrClassFile =
            @"---
--- Generated by Tools
--- Created by {0}.
--- DateTime: {1}
---

local BaseMediator = require('Game.Core.Ioc.BaseMediator')
---@class $CLASS_PACKER$.$CLASS_NAME$Mdr : Game.Core.Ioc.BaseMediator
---@field $Module_name$Model $MODULE_PACKER$.Model.$MODULE_NAME$Model
---@field $Module_name$Service $MODULE_PACKER$.Service.$MODULE_NAME$Service
local $CLASS_NAME$Mdr = class('$CLASS_PACKER$.$CLASS_NAME$Mdr',BaseMediator)

function $CLASS_NAME$Mdr:OnInit()
    
end

return $CLASS_NAME$Mdr
";

        //Model类文件
        public string LuaModelClassFile =
            @"---
--- Generated by Tools
--- Created by {0}.
--- DateTime: {1}
---

local BaseModel = require('Game.Core.Ioc.BaseModel')
---@class $CLASS_PACKER$.$CLASS_NAME$Model : Game.Core.Ioc.BaseModel
---@field $INSTANCE_NAME$Service $MODULE_PACKER$.Service.$CLASS_NAME$Service
local $CLASS_NAME$Model = class('$CLASS_PACKER$.$CLASS_NAME$Model',BaseModel)

function $CLASS_NAME$Model:Ctor()
    
end

return $CLASS_NAME$Model
";

        //Service类文件
        public string LuaServicelClassFile =
            @"---
--- Generated by Tools
--- Created by {0}.
--- DateTime: {1}
---

local BaseService = require('Game.Core.Ioc.BaseService')
---@class $CLASS_PACKER$.$CLASS_NAME$Service : Game.Core.Ioc.BaseService
---@field $INSTANCE_NAME$Model $MODULE_PACKER$.Model.$CLASS_NAME$Model
local $CLASS_NAME$Service = class('$CLASS_PACKER$.$CLASS_NAME$Service',BaseService)

function $CLASS_NAME$Service:Ctor()
    
end

return $CLASS_NAME$Service
";

        //Vo类文件
        public string LuaVoClassFile =
            @"---
--- Generated by Tools
--- Created by {0}.
--- DateTime: {1}
---

local BaseVo = require('Game.Core.BaseVo')
---@class $CLASS_PACKER$.$CLASS_NAME$Vo : Game.Core.BaseVo
---@field New fun():$CLASS_PACKER$.$CLASS_NAME$Vo
local $CLASS_NAME$Vo = class('$CLASS_PACKER$.$CLASS_NAME$Vo',BaseVo)

function $CLASS_NAME$Vo:Ctor()
    
end

return $CLASS_NAME$Vo
";
        
        //Cmooand类文件
        public string LuaCommandClassFile =
            @"---
--- Generated by Tools
--- Created by {0}.
--- DateTime: {1}
---

local BaseCommand = require('Game.Core.BaseCommand')
---@class $CLASS_PACKER$.$CLASS_NAME$Cmd : Game.Core.BaseCommand
---@field New fun():$CLASS_PACKER$.$CLASS_NAME$Cmd
---@field $Module_name$Model $MODULE_PACKER$.Model.$MODULE_NAME$Model
---@field $Module_name$Service $MODULE_PACKER$.Service.$MODULE_NAME$Service
local $CLASS_NAME$Cmd = class('$CLASS_PACKER$.$CLASS_NAME$Cmd',BaseCommand)

function $CLASS_NAME$Cmd:Ctor()
    
end

return $CLASS_NAME$Cmd
";
    }
}