---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/6/10 20:56
---

---UnityEngine
GameObject = UnityEngine.GameObject;

---Framework
logger = Logger
gameMgr = Framework.GameManager.GetGameManager()
assetsMgr = Framework.GameManager.GetAssetsManager()
sceneMgr = Framework.GameManager.GetSceneManager()

LuaHelper = Framework.LuaHelper