---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/6/10 20:56
---

---UnityEngine
GameObject = UnityEngine.GameObject;

---Framework
logger = Logger
gameMgr = Framework.BaseManager.GetGameManager()
assetsMgr = Framework.BaseManager.GetAssetsManager()