---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/7/13 1:28
--- 全局常量
---

ServerName = {}
ServerName.AccountServer = "AccountServer"
ServerName.GateServer = "GateServer"
ServerName.GameServer = "GameServer"
