---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/6/11 0:23
---

require "Core.Define"
require "Core.Function"

print("Global define has all require")