---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhengnan.
--- DateTime: 2018/6/20 16:29
---

---@class Core.List : Core.LuaObject
local LuaObject = require("Core.LuaObject")
local List = class("List",LuaObject)

local function Operator(list)
    local mt = getmetatable(list).__index
    setmetatable(list,
{__index = function (t,k)
        if type(k) == "number" and mt.At then
            return mt.At(t,k)
        end
    end})
end

function List:Ctor()
    Operator(self)
    self._array = {}
end

function List:Clear()
    self._array = nil
    self._array = {}
end

function List:Size()
    return  #self._array
end

function List:Add(item)
    table.insert(self._array,item)
end

function List:Insert(item,pos)
    if pos <= 0 then
        logError("List out of range")
    elseif pos >= #self._array then
        table.insert(self._array,item)
    else
        table.insert(self._array,pos,item)
    end
end

function List:RemoveAt(idx)
    return table.remove(self._array,idx)
end

function List:Shift()
    return table.remove(self._array,1)
end

function List:Pop()
    return table.remove(self._array,#self._array)
end

function List:Remove(item)
    if nil == item then
        logError("List remove a item that is not nil")
    else
        for i = 1,#self._array do
            if self._array[i] == item then
                table.remove(self._array,i)
                return
            end
        end
    end
end

function List:Contain(item)
    if nil == item then
        logError("List contain a item that is not nil")
        return false
    else
        for i = 1,#self._array do
            if self._array[i] == item then
                return true
            end
        end
    end
end

function List:At(idx)
    if idx <= 0 or idx > #self._array then
        logError("Index out of range. index")
        return false
    end
    return self._array[idx]
end

function List:Concat(other)
    return table.remove(self._array,idx)
end

return List