---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/6/12 0:43
---

--- 是否将日志输出到控制台
logger.GetInstance().LogInfoToConsole = true;
--- 是否输出一般日志的堆栈
logger.GetInstance().LogInfoTraceStack = false;
--- 是否输出到文本文件
logger.GetInstance().WriteToFile = true;

function log(msg,...)
    local arg = ...
    logger.Info(msg,arg)
end

function logError(msg,...)
    local arg = ...
    logger.Error(msg,arg)
end

function logWarn(msg,...)
    local arg = ...
    logger.Warning(msg,arg)
end