---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/6/14 0:22
--- LuaMonoBehaviour
---

---@class Core.LuaMonoBehaviour : Core.LuaObject
local LuaObject = require("Core.LuaObject")
local LuaMonoBehaviour = class("LuaMonoBehaviour",LuaObject)

local BehaviourFun = {"Awake","Start","OnEnable","OnDisable","OnDestroy","Update","LateUpdate","FixedUpdate"}

function LuaMonoBehaviour:Ctor()

end

function LuaMonoBehaviour:AddLuaMonoBehaviour(go,name)
    local behaviour = nil
    for k, v in pairs(BehaviourFun) do
        if self[v] then
            behaviour = LuaHelper.AddLuaMonoBehaviour(go,name,v,handler(self,self[v]))
        end
    end
    return behaviour
end

function LuaMonoBehaviour:LoadAsset(assetName)
    local prefab = assetsMgr:LoadPrefab(assetName)
    if prefab == nil then
        logStack()
    end
    return prefab
end

return LuaMonoBehaviour