---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/6/14 0:22
--- LuaMonoBehaviour
---

---@class Core.LuaMonoBehaviour : Core.LuaObject
local LuaObject = require("Core.LuaObject")
local LuaMonoBehaviour = class("LuaMonoBehaviour",LuaObject)

function LuaMonoBehaviour:Ctor()

end

function LuaMonoBehaviour:LoadAsset(assetName)
    local prefab = assetsMgr:LoadPrefab(assetName)
    if prefab == nil then
        logStack()
    end
    return prefab
end

return LuaMonoBehaviour