---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/6/14 0:17
--- Super class of all oop object classes
---

---@class Core.LuaObject
local LuaObject = class("LuaObject")

function LuaObject:Ctor()

end

function LuaObject:ToString()
    return type(self)
end

return LuaObject