---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/6/30 0:38
---

--是否是有效字符串
function string.isValid(s)
    return s ~= nil and s ~= ""
end

--是否是无效字符串
function string.isNullOrEmpty(s)
    return s == nil or s == ""
end

--替换
function string.replace(s,k,v)
    local index = string.find(s, k)
    if index ~= nil then
        s = string.sub(s,1,index - 1)..v..string.sub(s,index + string.len(k))
    end
    return s
end

--替换所有
function string.replaceAll(s,k,v)
    local index = string.find(s, k)
    while index ~= nil do
        s = string.replace(s,k,v)
        index = string.find(s, k)
    end
    return s
end

--首字母大写
function string.startUpper(s)
    local first = string.sub(s, 1, 1)
    return string.upper(first)..string.sub(s, 2)
end

--首字母小写
function string.startLower(s)
    local first = string.sub(s, 1, 1)
    return string.lower(first)..string.sub(s, 2)
end