---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zheng.
--- DateTime: 2018/6/11 0:11
---

local LuaClient = {}


function LuaClient.Start()
    LuaClient.RequireGlobalDefines()
    LuaClient.Test()
end

--加载全局定义
function LuaClient.RequireGlobalDefines()
    require "Core.init"
end


--启动测试代码
function LuaClient.Test()
    local timer = Timer.New(LuaClient.DoTestCo, 2, 1)
    timer:Start()
end

--启动测试代码
function LuaClient.DoTestCo()
    print("Timer" .. Time.time)
    local prefab = assetsMgr:LoadPrefab("Prefabs/UI/Login/LoginWnd.prefab");
    local go = GameObject.Instantiate(prefab);
    log("测试日志{0}","Info")
    logWarn("测试日志{0}","Warn")
    logError("测试日志{0}","Error")
end

return LuaClient

