---
--- Generated by Tools
--- Created by zhengnan.
--- DateTime: 2018-06-19-16:04:54
---

---@class Modules.Login.Model.LoginModel : Core.Ioc.BaseModel
local BaseModel = require("Core.Ioc.BaseModel")
local LoginModel = class("LoginModel",BaseModel)

function LoginModel:Ctor()
    
end

return LoginModel
