---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2018-08-14-22:15:40
---

---@class Modules.Loading.View.LoadingMdr : Core.Ioc.BaseMediator
local BaseMediator = require("Core.Ioc.BaseMediator")
local LoadingMdr = class("LoadingMdr",BaseMediator)
local WaitTime = 2

function LoadingMdr:OnInit()
    self:StartCoroutine(function ()
        local startTime = Time.time;
        while Time.time - startTime < WaitTime do
            coroutine.step(1)
            self.gameObject:SetSlider("LoadingBar", (Time.time - startTime) / WaitTime)
        end
        World.ins:EnterNextScene()
    end)
end

return LoadingMdr
