---
--- Generated by Tools
--- Created by zheng.
--- DateTime: 2018-08-14-00:09:39
---

---@class Modules.Role.View.RoleInfoMdr : Core.Ioc.BaseMediator
local BaseMediator = require("Core.Ioc.BaseMediator")
local RoleInfoMdr = class("RoleInfoMdr",BaseMediator)

function RoleInfoMdr:OnInit()
    self.mainRoleInfo = self.roleModel.mainRoleInfo;
    self.gameObject:SetText("TextRoleName", self.mainRoleInfo.roleName)
end

function RoleInfoMdr:Update()
    local totalTime = Mathf.Floor(self.mainRoleInfo:GetRealTotalOnlineTime())
    self.gameObject:SetText("TextOnlineTime", "在线:"..totalTime .. "秒")
end

return RoleInfoMdr
